#pragma config(Sensor, dgtl1,  EncoderLiftLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  EncoderLiftRight, sensorQuadEncoder)
#pragma config(Motor,  port1,           DriveFrontLeft, tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           DriveFrontRight, tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port3,           DriveRearLeft, tmotorVex393_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port4,           DriveRearRight, tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           LiftLeftA,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LiftLeftB,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           LiftRightA,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LiftRightB,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           CollectionA,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          CollectionB,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define NoLCD
#include "core\v3\competition.h"

int Lift_Target = 0;
const float Kp = 5;
const float Kd = 1;

void pre_auton() {
	SensorValue[EncoderLiftLeft] = 0;
	SensorValue[EncoderLiftRight] = 0;
}

int Normalize(int speed) {
	if(speed > 127) {
		return 127;
	}
	if(speed < -127) {
		return -127;
	}
	return speed;
}

void Set_Lift_Target() {
	Lift_Target = (SensorValue[EncoderLiftLeft] + SensorValue[EncoderLiftRight]) / 2;
}

task Lift_Stabilizer_Left {
	const tSensors sensor = EncoderLiftLeft;
	int error, previous_error, speed, derivative;
	while(true) {
		error = Lift_Target - SensorValue[sensor];
		derivative = error - previous_error;
		previous_error = error;
		speed = Kp * error + Kd * derivative;
		motor[LiftLeftA] = Normalize(speed);
		motor[LiftLeftB] = Normalize(speed);
	}
}

task Lift_Stabilizer_Right {
	const tSensors sensor = EncoderLiftRight;
	int error, previous_error, speed, derivative;
	while(true) {
		error = Lift_Target - SensorValue[sensor];
		derivative = error - previous_error;
		previous_error = error;
		speed = Kp * error + Kd * derivative;
		motor[LiftRightA] = Normalize(speed);
		motor[LiftRightB] = Normalize(speed);
	}
}

task usercontrol {
	while(true) {
		// DRIVE
		motor[DriveFrontLeft] = (vexRT[Ch3] + vexRT[Ch4]);
		motor[DriveFrontRight] = (vexRT[Ch3] - vexRT[Ch4]);
		motor[DriveRearLeft] = (vexRT[Ch3] + vexRT[Ch4]);
		motor[DriveRearRight] = (vexRT[Ch3] - vexRT[Ch4]);

		// LIFT
		if(vexRT[Btn6U] == 1) {
			stopTask(Lift_Stabilizer_Left);
			stopTask(Lift_Stabilizer_Right);
			Set_Lift_Target();
			motor[LiftLeftA] = 127;
			motor[LiftLeftB] = 127;
			motor[LiftRightA] = 127;
			motor[LiftRightB] = 127;
			} else if(vexRT[Btn6D] == 1) {
			stopTask(Lift_Stabilizer_Left);
			stopTask(Lift_Stabilizer_Right);
			Set_Lift_Target();
			motor[LiftLeftA] = -127;
			motor[LiftLeftB] = -127;
			motor[LiftRightA] = -127;
			motor[LiftRightB] = -127;
			} else {
			startTask(Lift_Stabilizer_Left);
			startTask(Lift_Stabilizer_Right);
		}

		// COLLECTION
		if(vexRT[Btn5U] == 1) {
			motor[CollectionA] = 127;
			motor[CollectionB] = 127;
			} else if(vexRT[Btn5D] == 1) {
			motor[CollectionA] = -127;
			motor[CollectionB] = -127;
			} else {
			motor[CollectionA] = 0;
			motor[CollectionB] = 0;
		}
	}
}
