#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in7,    PylonPot,       sensorPotentiometer)
#pragma config(Sensor, in8,    Gyroscope,      sensorGyro)
#pragma config(Sensor, dgtl1,  SolenoidCubes,  sensorDigitalOut)
#pragma config(Sensor, dgtl2,  SolenoidPylons, sensorDigitalOut)
#pragma config(Sensor, dgtl3,  LiftLimitMinA,  sensorTouch)
#pragma config(Sensor, dgtl4,  LiftLimitMinB,  sensorTouch)
#pragma config(Sensor, dgtl5,  MainBattLEDGreen, sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  MainBattLEDRed, sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  BackupBattLEDGreen, sensorLEDtoVCC)
#pragma config(Sensor, dgtl8,  BackupBattLEDRed, sensorLEDtoVCC)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Motor,  port1,           DriveCenterA,  tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port2,           LiftLeftTop,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           LiftRightTop,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           DriveFrontLeft, tmotorVex393HighSpeed_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port5,           DriveFrontRight, tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight, encoderPort, I2C_2)
#pragma config(Motor,  port6,           DriveRearLeft, tmotorVex393HighSpeed_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port7,           DriveRearRight, tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port8,           LiftLeftBottom, tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port9,           LiftRightBottom, tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port10,          DriveCenterB,  tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const string FILE = __FILE__;

#define NoPowerExpander
#define HasGyro
const tMotor LiftLeftA = LiftLeftTop;
const tMotor LiftLeftB = LiftLeftBottom;
const tMotor LiftLeftC = (tMotor)-1;
const tMotor LiftRightA = LiftRightTop;
const tMotor LiftRightB = LiftRightBottom;
const tMotor LiftRightC = (tMotor)-1;
const tSensors LiftEncoder = I2C_4;
const tSensors DriveEncoder = I2C_2;
#include "core\v3\batteryindicators.h"
#include "core\v3\core.h"
#include "misc\2105A-stabilizers.h"
//#include "auton\2105A-red-atloader.h"
#include "auton\2105A-red-freedom.h"
#include "misc\2105A-autonmanager.h"
#include "usercontrol\2105A-john.h"

void init() {
	SensorValue[I2C_1] = 0;
	SensorValue[I2C_2] = 0;
	SensorValue[I2C_3] = 0;
	SensorValue[I2C_4] = 0;
	nMotorEncoder[LiftLeftBottom] = 0;
	nMotorEncoder[LiftRightBottom] = 0;
	SensorValue[SolenoidPylons] = 0;
	SensorValue[SolenoidCubes] = 1;
	SensorValue[Gyroscope] = 0;
}

void ResetDriveEncoders() {
	nMotorEncoder[DriveCenterA] = 0;
	nMotorEncoder[DriveFrontRight] = 0;
	SensorValue[I2C_1] = 0;
	SensorValue[I2C_2] = 0;
}
