#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, dgtl1,  TransmissionPneumatic, sensorDigitalOut)
#pragma config(Sensor, dgtl2,  ClawPneumatic,  sensorDigitalOut)
#pragma config(Motor,  port1,           DriveLeftA,    tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           DriveLeftB,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           DriveRightA,   tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           DriveRightB,   tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           LiftA,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LiftB,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LiftC,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LiftD,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LiftE,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LiftF,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// This file should only include functions that are applicable to this robot across drivers and autonomous programs.
// Each driver gets his/her own file with usercontrol task
// Each autonomous function is in its own file that defines only that function
// Autonomous manager should also be in a seperate file?

#define NoProgrammingSkills
#define NoPowerExpander
#define NoInit
const string FILE = __FILE__;
#include "core\v3\core.h"
#include "usercontrol\2105A-john.h"

void ResetDriveEncoders() {}
