#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, dgtl1,  LiftLimitLeft,  sensorTouch)
#pragma config(Sensor, dgtl2,  LiftLimitRight, sensorTouch)
#pragma config(Sensor, dgtl3,  LiftEncoderLeft, sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  LiftEncoderRight, sensorQuadEncoder)
#pragma config(Motor,  port1,           DriveFrontLeft, tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           DriveFrontRight, tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           DriveRearLeft, tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           DriveRearRight, tmotorVex393_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port5,           LiftLeftA,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LiftLeftB,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LiftRightA,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LiftRightB,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           CollectionA,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          CollectionB,   tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "core\v3\competition.h"

void pre_auton() {}

int leftspeed = 127;
int rightspeed = 127;

task autonomous {
	motor[LiftLeftA] = -127;
	motor[LiftLeftB] = -127;
	motor[LiftRightA] = -80;
	motor[LiftRightB] = -80;
	wait1Msec(1200);
	motor[LiftLeftA] = 0;
	motor[LiftLeftB] = 0;
	motor[LiftRightA] = 0;
	motor[LiftRightB] = 0;

	motor[DriveFrontLeft] = 127;
	motor[DriveRearLeft] = 127;
	motor[DriveFrontRight] = 127;
	motor[DriveRearRight] = 127;
	wait1Msec(2100);
	motor[DriveFrontLeft] = -127;
	motor[DriveRearLeft] = -127;
	motor[DriveFrontRight] = 127;
	motor[DriveRearRight] = 127;
	wait1Msec(400);
	motor[DriveFrontLeft] = -127;
	motor[DriveRearLeft] = -127;
	motor[DriveFrontRight] = -127;
	motor[DriveRearRight] = -127;
	wait1Msec(600);
	motor[DriveFrontLeft] = 127;
	motor[DriveRearLeft] = 127;
	motor[DriveFrontRight] = -127;
	motor[DriveRearRight] = -127;
	wait1Msec(400);

	motor[DriveFrontLeft] = -127;
	motor[DriveRearLeft] = -127;
	motor[DriveFrontRight] = -127;
	motor[DriveRearRight] = -127;
	wait1Msec(1200);

	motor[DriveFrontLeft] = 127;
	motor[DriveRearLeft] = 127;
	motor[DriveFrontRight] = 127;
	motor[DriveRearRight] = 127;
	wait1Msec(600);
	allMotorsOff();
}

float multiplier = 1;
int pwm = 0;

task usercontrol {
	clearDebugStream();
	while(true) {
		if(vexRT[Btn8D] == 1) {
			multiplier = 0.2;
			} else {
			multiplier = 1;
		}
		motor[DriveFrontLeft] = (vexRT[Ch3] + vexRT[Ch4]) * multiplier;
		motor[DriveFrontRight] = (vexRT[Ch3] - vexRT[Ch4]) * multiplier;
		motor[DriveRearLeft] = (vexRT[Ch3] + vexRT[Ch4]) * multiplier;
		motor[DriveRearRight] = (vexRT[Ch3] - vexRT[Ch4]) * multiplier;
		//*
		pwm = (SensorValue[LiftEncoderLeft] - SensorValue[LiftEncoderRight]) * 0.5;
		if(pwm < -127) {
			pwm = -127;
		}
		if(pwm > 127) {
			pwm = 127;
		}
		if(vexRT[Btn8U] == 1) {
			pwm = 0;
		}
		//writeDebugStreamLine("PWM adjustment: %i",pwm);
		//*/
		// LIFT
		if(vexRT[Btn8R] == 1) {
			motor[LiftRightA] = 127;
			motor[LiftRightB] = 127;
			} else if(vexRT[Btn8L] == 1) {
			motor[LiftLeftA] = 127;
			motor[LiftLeftB] = 127;
			} else {

			if(vexRT[Btn6D] == 1) {
				/*
				motor[LiftLeftA] = leftspeed - pwm;
				motor[LiftLeftB] = leftspeed - pwm;
				motor[LiftRightA] = rightspeed + pwm;
				motor[LiftRightB] = rightspeed + pwm;//*/
				motor[LiftLeftA] = 127;
				motor[LiftLeftB] = 127;
				motor[LiftRightA] = 70;
				motor[LiftRightB] = 70;
				} else if(vexRT[Btn6U] == 1) {
				if(SensorValue[LiftLimitLeft] == 0) {
					motor[LiftLeftA] = -leftspeed - pwm;
					motor[LiftLeftB] = -leftspeed - pwm;
					} else {
					motor[LiftLeftA] = 0;
					motor[LiftLeftB] = 0;
				}
				if(SensorValue[LiftLimitRight] == 0) {
					motor[LiftRightA] = -rightspeed + pwm;
					motor[LiftRightB] = -rightspeed + pwm;
					} else {
					motor[LiftRightA] = 0;
					motor[LiftRightB] = 0;
				}
				} else {
				motor[LiftLeftA] = 0;
				motor[LiftLeftB] = 0;
				motor[LiftRightA] = 0;
				motor[LiftRightB] = 0;
			}
		}

		if(SensorValue[LiftLimitRight] == 1 && SensorValue[LiftLimitLeft] == 1) {
			SensorValue[LiftEncoderLeft] = 0;
			SensorValue[LiftEncoderRight] = 0;
		}

		// COLLECTION
		if(vexRT[Btn5U] == 1) {
			motor[CollectionA] = 127;
			motor[CollectionB] = 127;
			} else if(vexRT[Btn5D] == 1) {
			motor[CollectionA] = -127;
			motor[CollectionB] = -127;
			} else {
			motor[CollectionA] = 0;
			motor[CollectionB] = 0;
		}
	}
}
