#pragma config(Sensor, dgtl1,  TransmissionPneumatic, sensorDigitalOut)
#pragma config(Sensor, dgtl2,  ClawPneumatic,  sensorDigitalOut)
#pragma config(Motor,  port1,           DriveLeftA,    tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,           DriveLeftB,    tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port3,           DriveRightA,   tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           DriveRightB,   tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port5,           LiftA,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           LiftB,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LiftC,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LiftD,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LiftE,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LiftF,         tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define NoProgrammingSkills
#define NoPowerExpander
#define NoInit
#define NoLCD
const string FILE = __FILE__;
#include "core\v3\core.h"
#include "usercontrol\2105A.h"

void ResetDriveEncoders() {}
