#pragma config(Sensor, in1,    PowerExpander,  sensorAnalog)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define HasGyro
#define ProgrammingSkills
#include "core\v3\core.h"
#include "misc\core testing.h"
#include "auton\core testing.h"
#include "usercontrol\core testing.h"
