#pragma config(Sensor, dgtl1,  TransmissionPneumatic, sensorDigitalOut)
#pragma config(Sensor, dgtl2,  TransmissionLeftInner, sensorTouch)
#pragma config(Sensor, dgtl3,  TransmissionLeftOuter, sensorTouch)
#pragma config(Sensor, dgtl4,  TransmissionRightInner, sensorTouch)
#pragma config(Sensor, dgtl5,  TransmissionRightOuter, sensorTouch)
#pragma config(Motor,  port1,           DriveRight,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          DriveLeft,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

bool TransmissionState = false; // false = speed, true = torque; indicates whether actuator is pressurized or not

typedef enum {
    SPEED = 0,
    TORQUE = 1,
    TRANSITION = 2,
    STUCK = 3
} tTransmission;

task TransmissionControl {
    bool LastState = false;
    tTransmission Left = SPEED;
    tTransmission Right = SPEED;
    writeDebugStreamLine("Transmission control started");
    while (true) {
        if (!(TransmissionState == LastState)) {
            writeDebugStream("State change request recieved: switching to ");
            switch (TransmissionState) {
            case true:
                writeDebugStreamLine("torque");
                SensorValue[TransmissionPneumatic] = TransmissionState;
                writeDebugStreamLine("Pneumatic set to %i",TransmissionState);
                time1[T1] = 0;
                while (time1[T1] < 500) {
                    if (SensorValue[TransmissionLeftOuter] == 1 && SensorValue[TransmissionLeftInner] == 0 && !(Left == TORQUE)) {
                        Left = TORQUE;
                        writeDebugStreamLine("Left side has switched successfully");
                    }
                    if (SensorValue[TransmissionRightOuter] == 1 && SensorValue[TransmissionRightInner] == 0 && !(Right == TORQUE)) {
                        Right = TORQUE;
                        writeDebugStreamLine("Right side has switched successfully");
                    }
                    if ((Left == TORQUE) && (Right == TORQUE)) {
                        writeDebugStreamLine("Transmission is now in torque mode");
                        break;
                    }
                }
                if (SensorValue[TransmissionLeftInner] == 1 && SensorValue[TransmissionRightInner] == 1) {
                    writeDebugStreamLine("Out of air. Reboot to continue.");
                }
                writeDebugStreamLine("Finished transition.");
                break;
            case false:
                writeDebugStreamLine("speed");
                SensorValue[TransmissionPneumatic] = TransmissionState;
                writeDebugStreamLine("Pneumatic set to %i",TransmissionState);
                break;
            }
            LastState = TransmissionState;
        }
    }
}

task main {
    clearDebugStream();
    startTask(TransmissionControl);
    while (true) {
        //motor[DriveLeft] = vexRT[Ch3];
        //motor[DriveRight] = vexRT[Ch2];
        if (vexRT[Btn6U] == 1) {
            TransmissionState = false;
        }
        if (vexRT[Btn6D] == 1) {
            TransmissionState = true;
        }
    }
}
