#pragma config(Sensor, dgtl1,  TransmissionPneumatic, sensorDigitalOut)
#pragma config(Sensor, dgtl2,  TransmissionLeftInner, sensorTouch)
#pragma config(Sensor, dgtl3,  TransmissionLeftOuter, sensorTouch)
#pragma config(Sensor, dgtl4,  TransmissionRightInner, sensorTouch)
#pragma config(Sensor, dgtl5,  TransmissionRightOuter, sensorTouch)
#pragma config(Sensor, dgtl6,  Collector,      sensorTouch)
#pragma config(Motor,  port1,           DriveRight,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          DriveLeft,     tmotorVex393_HBridge, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main {
    while (true) {
        motor[DriveLeft] = vexRT[Ch3];
        motor[DriveRight] = vexRT[Ch2];
        if (vexRT[Btn6D] == 1) {
            SensorValue[TransmissionPneumatic] = 0;
        } else if (SensorValue[Collector] == 1) {
            SensorValue[TransmissionPneumatic] = 1;
       }
    }
}
