#pragma config(Motor,  port1,           DriveFrontLeft, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           DriveRearLeft, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           DriveFrontRight, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           DriveRearRight, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Middle,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while(true) {
		motor[DriveFrontLeft] = -(vexRT[Ch2] + vexRT[Ch4]);
		motor[DriveFrontRight] = (vexRT[Ch2] - vexRT[Ch4]);
		motor[DriveRearLeft] = -(vexRT[Ch2] + vexRT[Ch4]);
		motor[DriveRearRight] = (vexRT[Ch2] - vexRT[Ch4]);

		motor[Middle] = vexRT[Ch1];
	}
}
