#pragma config(Sensor, dgtl1,  PneumaticTransmission, sensorDigitalOut)
#pragma config(Motor,  port1,           LiftRightB,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LiftRightT,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           DriveRightL,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           DriveRightR,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           DriveLeftR,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           DriveLeftL,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LiftLeftT,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LiftLeftB,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int leftdrive, rightdrive;
task main {
	while (true) {
		leftdrive = vexRT[Ch2] + vexRT[Ch1];
		rightdrive = vexRT[Ch2] - vexRT[Ch1];
		motor[DriveLeftR] = leftdrive;
		motor[DriveLeftL] = leftdrive;
		motor[DriveRightR] = rightdrive;
		motor[DriveRightL] = rightdrive;

		//Lift
		if(vexRT[Btn5U] == 1) {
			motor[port5] = 127;
			} else if(vexRT[Btn5D] == 1) {
			motor[port5] = -127;
			} else {
			motor[port5] = 0;
		}

		//Lift
		if(vexRT[Btn6U] == 1) {
			motor[LiftLeftT] = 127;
			motor[LiftLeftB] = 127;

			motor[LiftRightT] = 127;
			motor[LiftRightB] = 127;

			} else if(vexRT[Btn6D] == 1) {
			motor[LiftLeftT] = -127;
			motor[LiftLeftB] = -127;

			motor[LiftRightT] = -127;
			motor[LiftRightB] = -127;

			}else{
			motor[LiftLeftT] = 0;
			motor[LiftLeftB] = 0;

			motor[LiftRightT] = 0;
			motor[LiftRightB] = 0;

		}

	}
}
