#pragma config(Sensor, dgtl1,  PneumaticTransmission, sensorDigitalOut)
#pragma config(Motor,  port1,           LiftRightB,    tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           LiftRightF,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           DriveRightL,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           DriveRightR,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           CollectionR,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           CollectionL,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           DriveLeftR,    tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           DriveLeftL,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LiftLeftF,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LiftLeftB,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "..\core\v3\competition.h"

void pre_auton() {}

int leftdrive, rightdrive;
task usercontrol {
	while (true) {
		leftdrive = vexRT[Ch3] + vexRT[Ch4];
		rightdrive = vexRT[Ch3] - vexRT[Ch4];
		motor[DriveLeftR] = leftdrive;
		motor[DriveLeftL] = leftdrive;
		motor[DriveRightR] = rightdrive;
		motor[DriveRightL] = rightdrive;

		//Lift
		if(vexRT[Btn5U] == 1) {
			motor[CollectionL] = 127;
			motor[CollectionR] = 127;
			} else if(vexRT[Btn5D] == 1) {
			motor[CollectionL] = -127;
			motor[CollectionR] = -127;
			} else {
			motor[CollectionL] = 0;
			motor[CollectionR] = 0;
		}

		//Lift
		if(vexRT[Btn8U] == 1) {
			motor[LiftLeftF] = 127;
			motor[LiftLeftB] = 127;
			motor[LiftRightF] = 127;
			motor[LiftRightB] = 127;
			} else if(vexRT[Btn7L] == 1) {
			motor[LiftLeftF] = -127;
			motor[LiftLeftB] = -127;
			motor[LiftRightF] = -127;
			motor[LiftRightB] = -127;
			}else{
			motor[LiftLeftF] = 0;
			motor[LiftLeftB] = 0;
			motor[LiftRightF] = 0;
			motor[LiftRightB] = 0;
		}
	}
}

task autonomous {
	//*
	motor[LiftLeftF] = 127;
	motor[LiftLeftB] = 127;
	motor[LiftRightF] = 127;
	motor[LiftRightB] = 127;//*/
	motor[CollectionL] = -30;
	motor[CollectionR] = -30;
	motor[DriveLeftR] = 127;
	motor[DriveLeftL] = 127;
	motor[DriveRightR] = 127;
	motor[DriveRightL] = 127;

	/*motor[DriveLeftR] = 127;
	motor[DriveLeftL] = 127;
	motor[DriveRightR] = 127;
	motor[DriveRightL] = 127;//*/
	wait1Msec(7000);

	motor[LiftLeftF] = 0;
	motor[LiftLeftB] = 0;
	motor[LiftRightF] = 0;
	motor[LiftRightB] = 0;

	motor[CollectionL] = 0;
	motor[CollectionR] = 0;

	motor[DriveLeftR] = 0;
	motor[DriveLeftL] = 0;
	motor[DriveRightR] = 0;
	motor[DriveRightL] = 0;

}
