#pragma config(Sensor, dgtl1,  PneumaticTransmission, sensorDigitalOut)
#pragma config(Motor,  port2,           DriveLeftA,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           DriveLeftB,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           DriveRightA,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           DriveRightB,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           LiftRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          LiftLeft,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main {
	while (true) {
		motor[DriveLeftA] = vexRT[Ch3];
		motor[DriveLeftB] = vexRT[Ch3];
		motor[DriveRightA] = vexRT[Ch2];
		motor[DriveRightB] = vexRT[Ch2];
		if (vexRT[Btn6D] == 1) {
			SensorValue[PneumaticTransmission] = 1;
			} else if (vexRT[Btn6U]) {
			SensorValue[PneumaticTransmission] = 0;
		}
		if(vexRT[Btn7U] == 1) {
			motor[LiftLeft] = 127;
			motor[LiftRight] = 127;
			} else if(vexRT[Btn7D] == 1) {
			motor[LiftLeft] = -127;
			motor[LiftRight] = -127;
			} else {
			motor[LiftLeft] = 0;
			motor[LiftRight ] = 0;
		}
	}
}
