#pragma config(Sensor, in1,    ,               sensorAnalog)
#pragma config(Sensor, in2,    ,               sensorAnalog)
#pragma config(Sensor, in3,    ,               sensorAnalog)
#pragma config(Sensor, in4,    ,               sensorAnalog)
#pragma config(Sensor, in5,    ,               sensorAnalog)
#pragma config(Sensor, in6,    ,               sensorAnalog)
#pragma config(Sensor, in7,    ,               sensorAnalog)
#pragma config(Sensor, in8,    ,               sensorAnalog)
#pragma config(Sensor, dgtl1,  ,               sensorTouch)
#pragma config(Sensor, dgtl2,  ,               sensorTouch)
#pragma config(Sensor, dgtl3,  ,               sensorTouch)
#pragma config(Sensor, dgtl4,  ,               sensorTouch)
#pragma config(Sensor, dgtl5,  ,               sensorTouch)
#pragma config(Sensor, dgtl6,  ,               sensorTouch)
#pragma config(Sensor, dgtl7,  ,               sensorTouch)
#pragma config(Sensor, dgtl8,  ,               sensorTouch)
#pragma config(Sensor, dgtl9,  ,               sensorTouch)
#pragma config(Sensor, dgtl10, ,               sensorTouch)
#pragma config(Sensor, dgtl11, ,               sensorTouch)
#pragma config(Sensor, dgtl12, ,               sensorTouch)
#pragma config(Motor,  port1,            ,             tmotorVex269_HBridge, openLoop)
#pragma config(Motor,  port2,            ,             tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,            ,             tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port4,            ,             tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,            ,             tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,            ,             tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex269_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while(true) {
		for(int speed = -127; speed <= 127; speed++) {
			for(int thismotor = 0; thismotor < 10; thismotor++) {
				motor[thismotor] = speed;
			}
			sleep(10);
		}
		for(int speed = 127; speed >= -127; speed--) {
			for(int thismotor = 0; thismotor < 10; thismotor++) {
				motor[thismotor] = speed;
			}
			sleep(10);
		}
	}
}
