#pragma config(Sensor, in1,    Gyro,           sensorGyro)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main {
	SensorValue[Gyro] = 0;
	while (true) {
		writeDebugStreamLine("Gyro sensor value: %i", SensorValue[Gyro]);
	}
}
