#pragma config(Sensor, dgtl1,  tankA,          sensorDigitalOut)
#pragma config(Sensor, dgtl2,  tankB,          sensorDigitalOut)
#pragma config(Sensor, dgtl3,  open,           sensorTouch)
#pragma config(Sensor, dgtl4,  close,          sensorTouch)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int counter = 0;
task main()
{
	while(true){
		if(SensorValue[open] == 1){
			SensorValue[tankA] = 1;
			SensorValue[tankB] = 1;
		} else if(SensorValue[close] == 1) {
		SensorValue[tankA] = 0;
		SensorValue[tankB] = 0;
		}
	}
}
