#pragma config(Motor,  port1,           Top,           tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,          Bottom,        tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while(true) {
		if(vexRT[Btn8U] == 1) {
			motor[Top] = 127;
			motor[Bottom] = 127;
			} else if(vexRT[Btn8D] == 1) {
			motor[Top] = -127;
			motor[Bottom] = -127;
			} else {
			motor[Top] = 0;
			motor[Bottom] = 0;
		}
	}
}
