void Auton_Blue_Freedom() {
	Auton_Lift_Targeted(UP,1200);
	sleep(500);
	Auton_Drive_Targeted(FORWARD,100);
	sleep(500);
	Auton_Drive_Targeted(LEFT,270);
	sleep(500);
	Auton_Drive_TurnTo(CLOCKWISE,-100,30);
	Auton_Lift_Targeted(DOWN,400);
	Auton_Drive_Targeted(BACKWARD,100);
	Auton_Drive_TurnTo(CLOCKWISE,-650);
	Auton_Lift_Targeted(DOWN,0);
	Auton_Drive_Targeted(FORWARD,30);
	Auton_Drive_TurnTo(CLOCKWISE,-1500);
	Auton_Drive_Targeted(FORWARD,300);
	Auton_Lift_Targeted(UP,200);
	Auton_Drive_TurnTo(COUNTERCLOCKWISE,0);
	Auton_Drive_Targeted(FORWARD,200);
	Auton_Lift_Targeted(1200);
	Auton_Drive_Targeted(FORWARD,100);
}
